database:
  type: "postgres"
  host: "host"
  port: 12345
  database-name: "database_name"
  username: "username"
  password: "password"

duration:
  keywords:
    permanent: ["permanently", "permanent", "perm"]
    day: ["days", "day", "d"]
    hour: ["hours", "hour", "hrs", "hr"]
    minute: ["minutes", "minute", "mins", "min", "m"]
    second: ["seconds", "second", "secs", "sec", "s"]
  display:
    permanent: "permanent"
    second-singular: "second"
    second-plural: "seconds"
    day-singular: "day"
    day-plural: "days"
    minute-singular: "minute"
    minute-plural: "minutes"
    hour-singular: "hour"
    hour-plural: "hours"
  suggestions: ["permanent", "365days", "30days", "1day", "12hours", "6hours", "30minutes"]

messages:
  internal-error: "Something went wrong."
  console-display-name: "[CONSOLE]"
  no-reason-fallback: "no reason provided"

  player-banned: "{issuer} banned {target} with reason {reason}."
  player-unbanned: "{issuer} unbanned {target} with reason {reason}."
  player-already-banned-error: "{target} is already banned."
  player-is-not-banned-error: "{target} is not banned."
  ban-screen: |
    You currently banned!
    Ban duration: {duration}

  player-muted: "{issuer} muted {target} with reason {reason}."
  player-unmuted: "{issuer} unmuted {target} with reason {reason}."
  player-already-muted-error: "{target} is already muted."
  player-is-not-muted-error: "{target} is not muted."
  muted-message: |
    You are currently muted!
    Mute duration: {duration}

# DO NOT TOUCH VERSION.
version: "0.0.1"
